import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { availableCableEnds, makeRuntime } from '../src/puzzle/collision';
import { removalSequenceIsValid } from '../src/puzzle/difficulty';
import { generatePuzzle } from '../src/puzzle/generator';
import { validatePuzzleGeometry } from '../src/puzzle/geometryValidation';
import { RUSH_CHALLENGES, RUSH_RANDOM_LINE_RATIO } from '../src/puzzle/rushChallenges';

const layouts = Object.fromEntries(RUSH_CHALLENGES.map((challenge) => {
  const referenceTargetCount = challenge.level.referenceTargetCount;
  if (!referenceTargetCount) throw new Error(`${challenge.id} has no random challenge reference count.`);
  const minimumReferenceCount = Math.ceil(referenceTargetCount * RUSH_RANDOM_LINE_RATIO);
  const warmup = challenge.level.targetCount < minimumReferenceCount;
  const sourceTargetCount = warmup ? challenge.level.targetCount : referenceTargetCount;
  const referenceLevel = {
    ...challenge.level,
    targetCount: sourceTargetCount,
    minInitiallyFree: warmup
      ? challenge.level.minInitiallyFree
      : Math.max(4, Math.floor(referenceTargetCount * 0.1)),
    maxInitiallyFree: warmup
      ? challenge.level.maxInitiallyFree
      : Math.min(18, Math.max(7, Math.ceil(referenceTargetCount * 0.42))),
    challengeKind: 'standard' as const,
  };
  let referencePuzzle: ReturnType<typeof generatePuzzle> | null = null;
  const generationAttempts = warmup ? 16 : 1;
  for (let attempt = 0; attempt < generationAttempts; attempt += 1) {
    const generationSeed = (challenge.level.seed + Math.imul(attempt, 7919)) >>> 0;
    const candidate = generatePuzzle(generationSeed, sourceTargetCount, {
      shape: challenge.level.shape,
      lengthQuota: challenge.level.lengthQuota,
      minInitiallyFree: referenceLevel.minInitiallyFree,
      maxInitiallyFree: referenceLevel.maxInitiallyFree,
      level: referenceLevel,
      mode: warmup ? 'rush' : 'random',
    });
    if (candidate.arrows.length !== sourceTargetCount) continue;
    if (
      warmup
      && (
        candidate.initiallyFree < referenceLevel.minInitiallyFree
        || candidate.initiallyFree > referenceLevel.maxInitiallyFree
      )
    ) continue;
    referencePuzzle = candidate;
    break;
  }
  if (!referencePuzzle) {
    throw new Error(`${challenge.id} could not satisfy its fixed count and opening-choice range.`);
  }
  if (referencePuzzle.arrows.length !== sourceTargetCount) {
    throw new Error(`${challenge.id} generated ${referencePuzzle.arrows.length}/${sourceTargetCount} source cables.`);
  }
  const solution = referencePuzzle.solution.slice(0, challenge.level.targetCount);
  const retainedIds = new Set(solution);
  const arrows = referencePuzzle.arrows.filter((arrow) => retainedIds.has(arrow.id));
  const initiallyFree = new Set(
    availableCableEnds(arrows.map(makeRuntime)).map(({ id }) => id),
  ).size;
  if (arrows.length !== challenge.level.targetCount) {
    throw new Error(`${challenge.id} retained ${arrows.length}/${challenge.level.targetCount} cables.`);
  }
  if (!removalSequenceIsValid(arrows, solution)) {
    throw new Error(`${challenge.id} cropped solution is invalid.`);
  }
  const geometryErrors = validatePuzzleGeometry(arrows);
  if (geometryErrors.length > 0) {
    throw new Error(`${challenge.id} cropped layout has ${geometryErrors.length} geometry errors.`);
  }
  return [challenge.id, {
    arrows,
    solution,
    initiallyFree,
  }];
}));

const source = `// Generated by scripts/generate-rush-layouts.ts. Do not edit by hand.\n`
  + `import type { ArrowDefinition } from './types';\n\n`
  + `export type FixedRushLayout = Readonly<{\n`
  + `  arrows: readonly ArrowDefinition[];\n`
  + `  solution: readonly string[];\n`
  + `  initiallyFree: number;\n`
  + `}>;\n\n`
  + `export const RUSH_LAYOUTS: Readonly<Record<string, FixedRushLayout>> = ${JSON.stringify(layouts, null, 2)};\n`;

const outputPath = resolve(process.cwd(), 'src/puzzle/rushLayouts.generated.ts');
writeFileSync(outputPath, source, 'utf8');
console.log(`Wrote ${Object.keys(layouts).length} fixed RUSH layouts to ${outputPath}`);
