import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generatePuzzle } from '../src/puzzle/generator';
import { availableCableEnds, makeRuntime } from '../src/puzzle/collision';
import { validatePuzzleGeometry } from '../src/puzzle/geometryValidation';
import { getRandomLevel } from '../src/puzzle/levels';
import type { LevelDefinition } from '../src/puzzle/types';

const targets = [34, 37, 40] as const;
const templates: Record<number, unknown> = {};
const seed = 2;
const base = getRandomLevel(seed);
const level: LevelDefinition = {
  ...base,
  seed,
  shape: 'cube',
  targetCount: 40,
  challengeKind: 'double-ended',
  referenceTargetCount: 50,
};
const puzzle = generatePuzzle(seed, 40, {
  shape: level.shape,
  lengthQuota: level.lengthQuota,
  minInitiallyFree: level.minInitiallyFree,
  maxInitiallyFree: level.maxInitiallyFree,
  level,
  mode: 'random',
  forceRegenerateDoubleEnded: true,
});
if (!puzzle.solutionEnds) throw new Error('Generated double-ended puzzle has no end-specific solution.');

// The reverse constructor deliberately produces a tightly focused dependency
// chain. Open one verified endpoint in its two-cable suffix so each derived
// template contains one rare three-choice beat instead of an all-binary rhythm.
const first = puzzle.arrows[0];
const expectedFirstPath = [[0, 7, 2], [0, 7, 0], [0, 10, 0], [2, 10, 0], [2, 7, 0], [2, 7, 1]];
if (JSON.stringify(first.path) !== JSON.stringify(expectedFirstPath)) {
  throw new Error('Seed-2 mother template changed; re-author the verified three-choice endpoint.');
}
first.path = [[0, 7, 2], [0, 7, 0], [0, 10, 0], [2, 10, 0], [2, 6, 0]];
first.exitDirection = '-Y';

for (const targetCount of targets) {
  const arrows = puzzle.arrows.slice(0, targetCount);
  const ids = new Set(arrows.map((arrow) => arrow.id));
  const solutionWithEnds = puzzle.solution.map((id, index) => ({
    id,
    end: puzzle.solutionEnds![index],
  })).filter((step) => ids.has(step.id));
  const geometryIssues = validatePuzzleGeometry(arrows);
  if (geometryIssues.length > 0) {
    throw new Error(`${targetCount}-cable template geometry: ${JSON.stringify(geometryIssues[0])}`);
  }

  const runtimes = arrows.map(makeRuntime);
  const choiceCounts: number[] = [];
  for (const step of solutionWithEnds) {
    const choices = availableCableEnds(runtimes);
    choiceCounts.push(choices.length);
    if (
      choices.length < 1 ||
      choices.length > 3 ||
      !choices.some((choice) => choice.id === step.id && choice.end === step.end)
    ) throw new Error(`${targetCount}-cable template has an invalid solution step ${step.id}:${step.end}.`);
    runtimes.find((runtime) => runtime.definition.id === step.id)!.state = 'removed';
  }
  if (!choiceCounts.includes(3)) throw new Error(`${targetCount}-cable template has no three-choice beat.`);
  if (choiceCounts.filter((count) => count <= 2).length / choiceCounts.length < 0.8) {
    throw new Error(`${targetCount}-cable template exposes too many three-choice steps.`);
  }

  templates[targetCount] = {
    arrows,
    solution: solutionWithEnds.map((step) => step.id),
    solutionEnds: solutionWithEnds.map((step) => step.end),
    initiallyFree: availableCableEnds(arrows.map(makeRuntime)).length,
  };
}

const source = `// Generated by scripts/generate-double-ended-templates.ts.\n` +
  `import type { DoubleEndedPuzzleTemplate } from './doubleEndedTemplates';\n\n` +
  `export const DOUBLE_ENDED_PUZZLE_TEMPLATES: Record<number, DoubleEndedPuzzleTemplate> = ${JSON.stringify(templates, null, 2)};\n`;
writeFileSync(resolve('src/puzzle/doubleEndedTemplates.generated.ts'), source, 'utf8');
