import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { diagnoseUnifiedRandomPuzzle } from '../src/puzzle/generator';
import { getRandomLevel } from '../src/puzzle/levels';
import { RANDOM_PUZZLE_TEMPLATES } from '../src/puzzle/randomTemplates.generated';
import type { RandomPuzzleTemplate } from '../src/puzzle/randomTemplates';
import type { GridExtents, LevelDefinition, ShapeId } from '../src/puzzle/types';

const templateSpecs: readonly {
  seed: number;
  shape: ShapeId;
  targetCount: number;
  halfExtents: GridExtents;
  attempts?: number;
}[] = [
  { seed: 44, shape: 'cube', targetCount: 42, halfExtents: [5, 5, 5] },
  { seed: 0x41002e, shape: 'cube', targetCount: 46, halfExtents: [5, 5, 5] },
  { seed: 0x410032, shape: 'cube', targetCount: 50, halfExtents: [5, 5, 5] },
  { seed: 0x410036, shape: 'cube', targetCount: 54, halfExtents: [5, 5, 5] },
  { seed: 0x41003a, shape: 'cube', targetCount: 58, halfExtents: [5, 5, 5], attempts: 12 },
  { seed: 42, shape: 'cylinder', targetCount: 42, halfExtents: [5, 5, 5] },
  { seed: 0x42002e, shape: 'cylinder', targetCount: 46, halfExtents: [5, 5, 5] },
  { seed: 0x420032, shape: 'cylinder', targetCount: 50, halfExtents: [5, 5, 5] },
  { seed: 0x420036, shape: 'cylinder', targetCount: 54, halfExtents: [5, 5, 5] },
  { seed: 0x42003a, shape: 'cylinder', targetCount: 58, halfExtents: [5, 5, 5], attempts: 12 },
  { seed: 0x43002a, shape: 'sphere', targetCount: 42, halfExtents: [5, 5, 5], attempts: 8 },
  { seed: 0x43002e, shape: 'sphere', targetCount: 46, halfExtents: [5, 5, 5] },
  { seed: 0x430032, shape: 'sphere', targetCount: 50, halfExtents: [5, 5, 5] },
  { seed: 0x430036, shape: 'sphere', targetCount: 54, halfExtents: [5, 5, 5] },
  { seed: 0x44002a, shape: 'octahedron', targetCount: 42, halfExtents: [5, 5, 5], attempts: 8 },
  { seed: 0x44002e, shape: 'octahedron', targetCount: 46, halfExtents: [5, 5, 5] },
  { seed: 0x440032, shape: 'octahedron', targetCount: 50, halfExtents: [5, 5, 5] },
  { seed: 0x440036, shape: 'octahedron', targetCount: 54, halfExtents: [5, 5, 5] },
  { seed: 0x45002a, shape: 'pyramid', targetCount: 42, halfExtents: [5, 5, 5], attempts: 8 },
  { seed: 0x45002e, shape: 'pyramid', targetCount: 46, halfExtents: [5, 5, 5] },
  { seed: 0x450032, shape: 'pyramid', targetCount: 50, halfExtents: [5, 5, 5] },
  { seed: 0x450036, shape: 'pyramid', targetCount: 54, halfExtents: [5, 5, 5] },
  { seed: 123456789, shape: 'cuboid', targetCount: 40, halfExtents: [5, 4, 5] },
  { seed: 0x46002e, shape: 'cuboid', targetCount: 46, halfExtents: [5, 4, 5] },
  { seed: 0x460034, shape: 'cuboid', targetCount: 52, halfExtents: [5, 4, 5] },
  { seed: 0x46003a, shape: 'cuboid', targetCount: 58, halfExtents: [5, 4, 5], attempts: 36 },
];
const outputPath = path.resolve('src/puzzle/randomTemplates.generated.ts');
const requested = new Set(process.argv.slice(2).filter((value) => value !== '--force'));
const force = process.argv.includes('--force');
const templates: Record<string, RandomPuzzleTemplate> = structuredClone(RANDOM_PUZZLE_TEMPLATES);
let failures = 0;

async function saveTemplates(): Promise<void> {
  const source = `// Generated by scripts/generate-random-templates.ts.\n` +
    `import type { RandomPuzzleTemplate } from './randomTemplates';\n\n` +
    `export const RANDOM_PUZZLE_TEMPLATES: Record<string, RandomPuzzleTemplate> = ${JSON.stringify(templates, null, 2)};\n`;
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, 'utf8');
}

for (const spec of templateSpecs) {
  const templateKey = `${spec.shape}-${spec.targetCount}`;
  if (requested.size > 0 && !requested.has(String(spec.seed)) && !requested.has(templateKey)) continue;
  if (!force && templates[templateKey]) {
    console.log(`Keeping existing random template ${templateKey}`);
    continue;
  }
  let accepted = false;
  const attemptLimit = spec.attempts ?? 18;
  for (let attempt = 0; attempt < attemptLimit; attempt += 1) {
    const seed = (spec.seed + Math.imul(attempt, 0x9e3779b1)) >>> 0;
    const level: LevelDefinition = {
      ...getRandomLevel(seed),
      shape: spec.shape,
      targetCount: spec.targetCount,
      halfExtents: spec.halfExtents,
      minSpans: spec.halfExtents.map((extent) => Math.max(4, extent * 2 - 2)) as GridExtents,
      minNeighborRatio: 0.38,
      minDensity: 0.2,
    };
    const startedAt = performance.now();
    const nearestBase = Object.entries(templates)
      .map(([key, template]) => {
        const match = key.match(/^([a-z-]+)-(\d+)$/);
        if (!match || match[1] !== spec.shape) return null;
        return { count: Number(match[2]), template };
      })
      .filter((entry): entry is { count: number; template: RandomPuzzleTemplate } =>
        entry !== null && entry.count < spec.targetCount)
      .sort((a, b) => b.count - a.count)[0];
    const result = diagnoseUnifiedRandomPuzzle(
      seed,
      level.targetCount,
      level,
      nearestBase?.template.arrows ?? [],
    );
    console.log(JSON.stringify({
      templateKey,
      attempt: attempt + 1,
      seed,
      baseCount: nearestBase?.count ?? 0,
      generatedCount: result.generatedCount,
      passed: Boolean(result.puzzle) && Object.values(result.checks).every(Boolean),
      checks: result.checks,
      generationMs: Math.round(performance.now() - startedAt),
    }));
    if (!result.puzzle || Object.values(result.checks).some((passed) => !passed)) continue;
    templates[templateKey] = {
      arrows: result.puzzle.arrows,
      solution: result.puzzle.solution,
      initiallyFree: result.puzzle.initiallyFree,
    };
    await saveTemplates();
    accepted = true;
    break;
  }
  if (!accepted) {
    failures += 1;
    console.error(`No accepted candidate for ${templateKey} after ${attemptLimit} attempts`);
  }
}

await saveTemplates();
console.log(`Wrote ${Object.keys(templates).length} random templates to ${outputPath}`);
if (failures > 0) process.exitCode = 1;
