import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  diagnoseUnifiedRandomPuzzle,
  generatePuzzle,
  prepareSkillTemplateCandidate,
} from '../src/puzzle/generator';
import { availableCableEnds, makeRuntime } from '../src/puzzle/collision';
import { freeDefinitions, removalSequenceIsValid } from '../src/puzzle/difficulty';
import { DOUBLE_ENDED_PUZZLE_TEMPLATES } from '../src/puzzle/doubleEndedTemplates.generated';
import type { DoubleEndedPuzzleTemplate } from '../src/puzzle/doubleEndedTemplates';
import { EXPLORATION_PUZZLE_TEMPLATES } from '../src/puzzle/explorationTemplates.generated';
import {
  allPlugEndpointDirectionsAreValid,
  validatePuzzleGeometry,
} from '../src/puzzle/geometryValidation';
import {
  getDoubleEndedLevel,
  getSkillChallengeLevel,
  getStandardRandomLevel,
  RANDOM_CHALLENGE_PROFILES,
} from '../src/puzzle/levels';
import { SKILL_PUZZLE_TEMPLATES } from '../src/puzzle/skillTemplates.generated';
import type { RandomPuzzleTemplate } from '../src/puzzle/randomTemplates';
import {
  directionKeyFromDelta,
  type GridExtents,
  type GridPoint,
  type LevelDefinition,
} from '../src/puzzle/types';

type SingleMode = 'exploration' | 'skill';

const outputPaths = {
  exploration: path.resolve('src/puzzle/explorationTemplates.generated.ts'),
  skill: path.resolve('src/puzzle/skillTemplates.generated.ts'),
  doubleEnded: path.resolve('src/puzzle/doubleEndedTemplates.generated.ts'),
};
const requested = new Set(process.argv.slice(2));
const buildExploration = requested.size === 0 || requested.has('--exploration') || requested.has('--single');
const buildSkill = requested.size === 0 || requested.has('--skill') || requested.has('--single');
const buildDoubleEnded = requested.size === 0 || requested.has('--double-ended');

function normalizePool<T>(value: T | readonly T[] | undefined): T[] {
  if (!value) return [];
  return Array.isArray(value) ? [...value] : [value as T];
}

const explorationTemplates: Record<string, RandomPuzzleTemplate[]> = Object.fromEntries(
  Object.entries(EXPLORATION_PUZZLE_TEMPLATES).map(([key, value]) => [key, normalizePool(value)]),
);
const skillTemplates: Record<string, RandomPuzzleTemplate[]> = Object.fromEntries(
  Object.entries(SKILL_PUZZLE_TEMPLATES).map(([key, value]) => [key, normalizePool(value)]),
);
const doubleEndedTemplates: Record<number, DoubleEndedPuzzleTemplate[]> = Object.fromEntries(
  Object.entries(DOUBLE_ENDED_PUZZLE_TEMPLATES).map(([key, value]) => [Number(key), normalizePool(value)]),
);

const profiles = [...new Map(
  RANDOM_CHALLENGE_PROFILES.map((profile) => [`${profile.shape}-${profile.targetCount}`, profile] as const),
).entries()].map(([key, profile]) => ({ key, ...profile }));

function topologySignature(template: RandomPuzzleTemplate | DoubleEndedPuzzleTemplate): string {
  return template.arrows
    .map((arrow) => arrow.path.map((point) => point.join(',')).join(';'))
    .join('|');
}

function makeLevel(
  mode: SingleMode,
  seed: number,
  profile: (typeof profiles)[number],
): LevelDefinition {
  const base = mode === 'skill' ? getSkillChallengeLevel(seed) : getStandardRandomLevel(seed);
  return {
    ...base,
    seed,
    shape: profile.shape,
    targetCount: profile.targetCount,
    halfExtents: profile.halfExtents,
    minSpans: profile.halfExtents.map((extent) => Math.max(4, extent * 2 - 2)) as GridExtents,
    minInitiallyFree: mode === 'skill' ? 4 : Math.max(4, Math.floor(profile.targetCount * 0.1)),
    maxInitiallyFree: mode === 'skill'
      ? 8
      : Math.min(18, Math.max(7, Math.ceil(profile.targetCount * (profile.maxFreeRatio ?? 0.24)))),
    minDensity: profile.minDensity ?? 0.28,
    challengeKind: 'standard',
    referenceTargetCount: profile.targetCount,
  };
}

function validSingleTemplate(
  template: RandomPuzzleTemplate,
  level: LevelDefinition,
  skill: boolean,
): boolean {
  const freeCount = freeDefinitions(template.arrows).length;
  return template.arrows.length === level.targetCount
    && validatePuzzleGeometry(template.arrows).length === 0
    && allPlugEndpointDirectionsAreValid(template.arrows)
    && removalSequenceIsValid(template.arrows, template.solution)
    && template.initiallyFree === freeCount
    && (!skill || (freeCount >= 4 && freeCount <= 8));
}

async function saveSingleTemplates(mode: SingleMode): Promise<void> {
  const templates = mode === 'skill' ? skillTemplates : explorationTemplates;
  const typeName = 'RandomPuzzleTemplatePool';
  const exportName = mode === 'skill' ? 'SKILL_PUZZLE_TEMPLATES' : 'EXPLORATION_PUZZLE_TEMPLATES';
  const source = `// Generated by scripts/generate-challenge-layouts.ts.\n`
    + `import type { ${typeName} } from './randomTemplates';\n\n`
    + `export const ${exportName}: Record<string, ${typeName}> = ${JSON.stringify(templates, null, 2)};\n`;
  const outputPath = outputPaths[mode];
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, 'utf8');
}

async function generateSingleMode(mode: SingleMode): Promise<void> {
  const templates = mode === 'skill' ? skillTemplates : explorationTemplates;
  const requiredVariants = mode === 'skill' ? 2 : 1;
  const globalSignatures = new Set<string>([
    ...Object.values(explorationTemplates).flat().map(topologySignature),
    ...Object.values(skillTemplates).flat().map(topologySignature),
  ]);

  for (const profile of profiles) {
    const pool = templates[profile.key] ?? [];
    templates[profile.key] = pool;
    for (const existing of [...pool]) {
      const level = makeLevel(mode, 0, profile);
      if (!validSingleTemplate(existing, level, mode === 'skill')) {
        pool.splice(pool.indexOf(existing), 1);
        globalSignatures.delete(topologySignature(existing));
      }
    }

    while (pool.length < requiredVariants) {
      const slot = pool.length;
      let accepted: RandomPuzzleTemplate | null = null;
      for (let attempt = 0; attempt < 48 && !accepted; attempt += 1) {
        const seed = (
          0x52000000
          + Math.imul(profiles.indexOf(profile) + 1, 0x10001)
          + Math.imul(slot + 1, 0x1f123)
          + Math.imul(attempt + 1, 0x9e3779b1)
          + (mode === 'skill' ? 0x13579bdf : 0x2468ace0)
        ) >>> 0;
        const level = makeLevel(mode, seed, profile);
        const base = generatePuzzle(seed ^ 0xa511e9b3, profile.targetCount, {
          shape: level.shape,
          lengthQuota: level.lengthQuota,
          minInitiallyFree: mode === 'skill' ? 4 : level.minInitiallyFree,
          maxInitiallyFree: mode === 'skill' ? 8 : level.maxInitiallyFree,
          level,
          mode: 'random',
          templateMode: 'random',
        });
        const minimumDrop = profile.targetCount >= 54 ? 2 : 5;
        const dropRange = profile.targetCount >= 54 ? 3 : 6;
        const dropCount = Math.min(
          profile.targetCount - 24,
          minimumDrop + ((attempt + slot * 3 + profiles.indexOf(profile)) % dropRange),
        );
        const prefix = base.arrows.slice(0, profile.targetCount - dropCount);
        const result = diagnoseUnifiedRandomPuzzle(seed, profile.targetCount, level, prefix);
        if (!result.puzzle || Object.values(result.checks).some((passed) => !passed)) {
          console.log(JSON.stringify({ mode, key: profile.key, slot, attempt: attempt + 1, seed, generated: result.generatedCount }));
          continue;
        }
        const prepared = mode === 'skill'
          ? prepareSkillTemplateCandidate(result.puzzle.arrows, result.puzzle.solution, level)
          : {
              arrows: result.puzzle.arrows,
              solution: result.puzzle.solution,
              initiallyFree: result.puzzle.initiallyFree,
            };
        if (!prepared || !validSingleTemplate(prepared, level, mode === 'skill')) continue;
        const signature = topologySignature(prepared);
        if (globalSignatures.has(signature)) continue;
        accepted = prepared;
        globalSignatures.add(signature);
        console.log(JSON.stringify({
          mode,
          key: profile.key,
          slot,
          attempt: attempt + 1,
          seed,
          initiallyFree: prepared.initiallyFree,
        }));
      }
      if (!accepted) throw new Error(`Unable to generate ${mode} template ${profile.key} variant ${slot}.`);
      pool.push(accepted);
      await saveSingleTemplates(mode);
    }
  }
  await saveSingleTemplates(mode);
}

function deriveDoubleEndedTemplate(
  mother: DoubleEndedPuzzleTemplate,
  targetCount: number,
): DoubleEndedPuzzleTemplate | null {
  const arrows = mother.arrows.slice(0, targetCount);
  const ids = new Set(arrows.map((arrow) => arrow.id));
  const steps = mother.solution.map((id, index) => ({ id, end: mother.solutionEnds[index] }))
    .filter(({ id }) => ids.has(id));
  const template: DoubleEndedPuzzleTemplate = {
    arrows,
    solution: steps.map(({ id }) => id),
    solutionEnds: steps.map(({ end }) => end),
    initiallyFree: availableCableEnds(arrows.map(makeRuntime)).length,
  };
  if (validatePuzzleGeometry(arrows).length > 0 || !allPlugEndpointDirectionsAreValid(arrows)) return null;
  const runtimes = arrows.map(makeRuntime);
  for (let index = 0; index < template.solution.length; index += 1) {
    const choices = availableCableEnds(runtimes);
    if (choices.length < 1 || choices.length > 3) return null;
    if (!choices.some(({ id, end }) => id === template.solution[index] && end === template.solutionEnds[index])) {
      return null;
    }
    runtimes.find((runtime) => runtime.definition.id === template.solution[index])!.state = 'removed';
  }
  return template;
}

async function saveDoubleEndedTemplates(): Promise<void> {
  const source = `// Generated by scripts/generate-challenge-layouts.ts.\n`
    + `import type { DoubleEndedPuzzleTemplatePool } from './doubleEndedTemplates';\n\n`
    + `export const DOUBLE_ENDED_PUZZLE_TEMPLATES: Record<number, DoubleEndedPuzzleTemplatePool> = ${JSON.stringify(doubleEndedTemplates, null, 2)};\n`;
  await writeFile(outputPaths.doubleEnded, source, 'utf8');
}

function segmentVector(start: GridPoint, end: GridPoint): GridPoint {
  return [end[0] - start[0], end[1] - start[1], end[2] - start[2]];
}

function compressPath(path: readonly GridPoint[]): GridPoint[] {
  const result: GridPoint[] = [];
  for (const point of path) {
    const cloned = [...point] as GridPoint;
    if (result.length < 2) {
      result.push(cloned);
      continue;
    }
    const previousVector = segmentVector(result[result.length - 2], result[result.length - 1]);
    const nextVector = segmentVector(result[result.length - 1], cloned);
    const previousAxis = previousVector.findIndex((value) => value !== 0);
    const nextAxis = nextVector.findIndex((value) => value !== 0);
    if (
      previousAxis >= 0
      && previousAxis === nextAxis
      && Math.sign(previousVector[previousAxis]) === Math.sign(nextVector[nextAxis])
    ) {
      result[result.length - 1] = cloned;
    } else {
      result.push(cloned);
    }
  }
  return result;
}

function permutations<T>(items: readonly T[]): T[][] {
  if (items.length <= 1) return [[...items]];
  return items.flatMap((item, index) => permutations([
    ...items.slice(0, index),
    ...items.slice(index + 1),
  ]).map((tail) => [item, ...tail]));
}

function localRouteVariants(definition: DoubleEndedPuzzleTemplate['arrows'][number]): GridPoint[][] {
  const variants: GridPoint[][] = [];
  const seen = new Set<string>();
  const originalKey = definition.path.map((point) => point.join(',')).join(';');
  for (let startIndex = 0; startIndex < definition.path.length - 2; startIndex += 1) {
    const maximumEnd = Math.min(definition.path.length - 1, startIndex + 4);
    for (let endIndex = startIndex + 2; endIndex <= maximumEnd; endIndex += 1) {
      const vectors = definition.path
        .slice(startIndex, endIndex + 1)
        .slice(0, -1)
        .map((point, index) => segmentVector(point, definition.path[startIndex + index + 1]));
      for (const ordered of permutations(vectors)) {
        const rebuilt: GridPoint[] = [[...definition.path[startIndex]] as GridPoint];
        for (const vector of ordered) {
          const previous = rebuilt[rebuilt.length - 1];
          rebuilt.push([
            previous[0] + vector[0],
            previous[1] + vector[1],
            previous[2] + vector[2],
          ]);
        }
        const path = compressPath([
          ...definition.path.slice(0, startIndex),
          ...rebuilt,
          ...definition.path.slice(endIndex + 1),
        ]);
        if (path.length < 2 || path.some((point) => point.some((value) => value < 0 || value > 10))) continue;
        const key = path.map((point) => point.join(',')).join(';');
        if (key === originalKey || seen.has(key)) continue;
        seen.add(key);
        variants.push(path);
      }
    }
  }
  return variants;
}

function rerouteDoubleEndedArrow(
  mother: DoubleEndedPuzzleTemplate,
  arrowIndex: number,
  path: GridPoint[],
): DoubleEndedPuzzleTemplate {
  const arrows = mother.arrows.map((arrow, index) => {
    if (index !== arrowIndex) return arrow;
    const head = path[path.length - 1];
    const previous = path[path.length - 2];
    return {
      ...arrow,
      path,
      exitDirection: directionKeyFromDelta([
        Math.sign(head[0] - previous[0]),
        Math.sign(head[1] - previous[1]),
        Math.sign(head[2] - previous[2]),
      ]),
    };
  });
  return { ...mother, arrows };
}

function locallyMutatedMother(
  source: DoubleEndedPuzzleTemplate,
  changeCount: number,
  variantSalt: number,
  rejectedSignatures: ReadonlySet<string>,
): DoubleEndedPuzzleTemplate | null {
  let visited = 0;
  const maximumVisited = 12_000;
  const search = (
    current: DoubleEndedPuzzleTemplate,
    changedIds: ReadonlySet<string>,
  ): DoubleEndedPuzzleTemplate | null => {
    if (visited >= maximumVisited) return null;
    visited += 1;
    if (changedIds.size >= changeCount) {
      const signature = topologySignature(current);
      if (rejectedSignatures.has(signature)) return null;
      return [34, 37, 40].every((target) => deriveDoubleEndedTemplate(current, target))
        ? current
        : null;
    }

    const orderedIndexes = current.arrows.map((_, index) => index).sort((left, right) => {
      const leftRank = Math.imul((left + 1) ^ variantSalt ^ changedIds.size, 0x45d9f3b) >>> 0;
      const rightRank = Math.imul((right + 1) ^ variantSalt ^ changedIds.size, 0x45d9f3b) >>> 0;
      return leftRank - rightRank;
    });
    for (const arrowIndex of orderedIndexes) {
      const arrow = current.arrows[arrowIndex];
      if (changedIds.has(arrow.id)) continue;
      const variants = localRouteVariants(arrow);
      for (let routeIndex = 0; routeIndex < Math.min(variants.length, 24); routeIndex += 1) {
        const candidate = rerouteDoubleEndedArrow(current, arrowIndex, variants[routeIndex]);
        if (!deriveDoubleEndedTemplate(candidate, 40)) continue;
        const nextChanged = new Set(changedIds);
        nextChanged.add(arrow.id);
        const result = search(candidate, nextChanged);
        if (result) return result;
      }
    }
    return null;
  };
  return search(source, new Set<string>());
}

async function generateDoubleEndedMode(): Promise<void> {
  const targets = [34, 37, 40] as const;
  const motherSignatures = new Set(
    (doubleEndedTemplates[40] ?? []).map(topologySignature),
  );
  const originalMother = normalizePool<DoubleEndedPuzzleTemplate>(
    DOUBLE_ENDED_PUZZLE_TEMPLATES[40],
  )[0];
  if (!originalMother) throw new Error('Missing verified 40-cable double-ended mother template.');
  while (targets.some((target) => (doubleEndedTemplates[target]?.length ?? 0) < 4)) {
    const variantIndex = doubleEndedTemplates[40]?.length ?? 1;
    const mother = locallyMutatedMother(
      originalMother,
      Math.min(4, variantIndex + 1),
      0x4d2 + variantIndex * 97,
      motherSignatures,
    );
    if (!mother) throw new Error(`Unable to author double-ended local topology variant ${variantIndex}.`);
    const derived = targets.map((target) => deriveDoubleEndedTemplate(mother, target));
    if (derived.some((template) => template === null)) {
      throw new Error(`Double-ended local topology variant ${variantIndex} failed derivation.`);
    }
    targets.forEach((target, index) => {
      const pool = doubleEndedTemplates[target] ?? [];
      doubleEndedTemplates[target] = pool;
      if (pool.length < 4) pool.push(derived[index]!);
    });
    motherSignatures.add(topologySignature(mother));
    console.log(JSON.stringify({
      mode: 'double-ended',
      variant: variantIndex,
      changedCables: Math.min(4, variantIndex + 1),
    }));
    await saveDoubleEndedTemplates();
  }
  await saveDoubleEndedTemplates();
}

if (buildExploration) await generateSingleMode('exploration');
if (buildSkill) await generateSingleMode('skill');
if (buildDoubleEnded) await generateDoubleEndedMode();

console.log(JSON.stringify({
  exploration: Object.values(explorationTemplates).reduce((total, pool) => total + pool.length, 0),
  skill: Object.values(skillTemplates).reduce((total, pool) => total + pool.length, 0),
  doubleEnded: Object.values(doubleEndedTemplates).reduce((total, pool) => total + pool.length, 0),
}));
