import { mkdirSync, writeFileSync } from 'node:fs';
import * as THREE from 'three';
import { createHumidifierModel } from '../src/appliances/models/humidifier';

const build = createHumidifierModel({ id: 'humidifier', accent: 0xe8a7b7 }); const parts: Array<{ name: string; kind: string; triangles: number }> = []; let unnamedMeshes = 0;
build.root.traverse((node) => { if (!(node instanceof THREE.Mesh) || node.userData.isOutline) return; if (!node.name) unnamedMeshes += 1; const position = node.geometry.getAttribute('position'); parts.push({ name: node.name || '(unnamed)', kind: 'mesh', triangles: Math.round(node.geometry.index ? node.geometry.index.count / 3 : position.count / 3) }); });
const runtime = build.root.userData.sculptRuntime as { nodes: Record<string, THREE.Object3D> }; for (const name of ['humidifier-outlet-cap-pivot', 'humidifier-mist-outlet-socket', 'humidifier-control-dial-pivot', 'humidifier-volumetric-mist-rig', 'humidifier-volumetric-weather-cloud-rig', 'humidifier-volumetric-rain-rig']) parts.push({ name, kind: name.endsWith('socket') ? 'socket' : 'pivot', triangles: 0 });
const specified = ['humidifier-lower-body-shell', 'humidifier-bottom-accent-rail', 'humidifier-transparent-water-reservoir', 'humidifier-tank-body-seam', 'humidifier-outlet-recess-seat', 'humidifier-outlet-rotary-cap', 'humidifier-front-control-panel', 'humidifier-control-dial', 'humidifier-rear-service-panel', 'humidifier-rear-drain-cover', 'humidifier-volumetric-weather-cloud-lobe-1', 'humidifier-rain-drop-1']; const names = new Set(parts.map((part) => part.name)); const missing = specified.filter((name) => !names.has(name) || !runtime.nodes[name]);
const manifest = { model: 'humidifier', parts: parts.sort((a, b) => a.name.localeCompare(b.name)), unnamedMeshes }; const coverage = { model: 'humidifier', passed: missing.length === 0 && unnamedMeshes === 0, specified: specified.length, covered: specified.length - missing.length, missing, unnamedMeshes, note: 'Coverage proves the named assembly exists; visual fidelity is evaluated separately from screenshots.' };
mkdirSync('artifacts/appliance-v2/humidifier/assembly', { recursive: true }); writeFileSync('artifacts/appliance-v2/humidifier/assembly/parts-manifest.json', `${JSON.stringify(manifest, null, 2)}\n`); writeFileSync('artifacts/appliance-v2/humidifier/assembly/part-coverage.json', `${JSON.stringify(coverage, null, 2)}\n`); console.log(JSON.stringify(coverage, null, 2)); build.root.traverse((object) => { if (object instanceof THREE.Mesh) object.geometry.dispose(); }); build.materials.forEach((material) => material.dispose()); if (!coverage.passed) process.exitCode = 1;
