import { mkdirSync, writeFileSync } from 'node:fs';
import * as THREE from 'three';
import { createRecordPlayerModel } from '../src/appliances/models/recordPlayer';

const build = createRecordPlayerModel({ id: 'record-player', accent: 0xe8a7b7 }); const parts: Array<{ name: string; kind: string; triangles: number }> = []; let unnamedMeshes = 0;
build.root.traverse((node) => { if (!(node instanceof THREE.Mesh) || node.userData.isOutline) return; if (!node.name) unnamedMeshes += 1; const position = node.geometry.getAttribute('position'); parts.push({ name: node.name || '(unnamed)', kind: 'mesh', triangles: Math.round(node.geometry.index ? node.geometry.index.count / 3 : position.count / 3) }); });
const runtime = build.root.userData.sculptRuntime as { nodes: Record<string, THREE.Object3D> };
const specified = ['record-player-rounded-body-shell', 'record-player-body-side-facet-1', 'record-player-top-deck', 'record-player-front-grille-panel', 'record-player-front-speaker-badge', 'record-player-raised-lid-shell', 'record-player-lid-side-spine-1', 'record-player-transparent-lid-panel', 'record-player-black-vinyl-platter', 'record-player-vinyl-groove-1', 'record-player-center-spindle', 'record-player-tonearm-base', 'record-player-tonearm-counterweight', 'record-player-tonearm-rise', 'record-player-tonearm-sweep', 'record-player-pink-cartridge', 'record-player-stylus-tip', 'record-player-speed-control-knob', 'record-player-recessed-carry-handle', 'record-player-rear-io-plate', 'record-player-performance-effects'];
const names = new Set(parts.map((part) => part.name)); const missing = specified.filter((name) => !runtime.nodes[name] || (!names.has(name) && name !== 'record-player-performance-effects'));
const manifest = { model: 'record-player', parts: parts.sort((a, b) => a.name.localeCompare(b.name)), unnamedMeshes }; const coverage = { model: 'record-player', passed: missing.length === 0 && unnamedMeshes === 0, specified: specified.length, covered: specified.length - missing.length, missing, unnamedMeshes, note: 'Coverage proves the named assembly exists; screenshot review separately evaluates appearance and animation contact.' };
mkdirSync('artifacts/appliance-v2/record-player/assembly', { recursive: true }); writeFileSync('artifacts/appliance-v2/record-player/assembly/parts-manifest.json', `${JSON.stringify(manifest, null, 2)}\n`); writeFileSync('artifacts/appliance-v2/record-player/assembly/part-coverage.json', `${JSON.stringify(coverage, null, 2)}\n`); console.log(JSON.stringify(coverage, null, 2));
build.root.traverse((object) => { if (object instanceof THREE.Mesh) object.geometry.dispose(); }); build.materials.forEach((material) => material.dispose()); if (!coverage.passed) process.exitCode = 1;
